"""Pydantic data models and schemas for the production API."""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ==========================================
# 1. Enums & Base Primitives
# ==========================================

class MessageRole(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ChatMessage(BaseModel):
    """Single chat message representing conversation turn history."""
    role: MessageRole = Field(..., description="Role of the message sender")
    content: str = Field(..., description="Content of the message")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# ==========================================
# 2. Token Usage & Observability Models
# ==========================================

class TokenUsage(BaseModel):
    """Token consumption and cost metrics."""
    prompt_tokens: int = Field(default=0, description="Tokens used in prompt/context")
    completion_tokens: int = Field(default=0, description="Tokens generated by model")
    total_tokens: int = Field(default=0, description="Total tokens used")
    estimated_cost_usd: Optional[float] = Field(default=None, description="Estimated USD cost")


class MetricsResponse(BaseModel):
    """Metrics endpoint response."""
    total_requests: int = Field(..., description="Total requests processed")
    total_errors: int = Field(default=0, description="Total error count")
    error_rate: str = Field(..., description="Error rate percentage formatted as string")
    avg_latency_ms: float = Field(..., description="Average latency in ms")
    cache_hit_rate: str = Field(..., description="Cache hit rate percentage formatted as string")
    total_input_tokens: int = Field(default=0, description="Total input tokens consumed")
    total_output_tokens: int = Field(default=0, description="Total output tokens generated")


class SourceDocument(BaseModel):
    """Source reference / chunk cited in RAG response."""
    document_id: Optional[str] = Field(default=None, description="ID of source document")
    title: Optional[str] = Field(default=None, description="Title or file name")
    content: str = Field(..., description="Relevant chunk or snippet content")
    score: Optional[float] = Field(default=None, description="Similarity or reranking score")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata tags, page numbers, URLs")


# ==========================================
# 3. Chat & Agent Request / Response Models
# ==========================================

class ChatRequest(BaseModel):
    """Incoming user query payload."""
    message: str = Field(..., min_length=1, description="User query or prompt")
    user_id: Optional[str] = Field(default=None, description="Identifier for user")
    session_id: Optional[str] = Field(default=None, description="Conversation thread ID")
    history: Optional[List[ChatMessage]] = Field(default=None, description="Prior conversation context")
    use_cache: bool = Field(default=True, description="Whether to check semantic cache")
    temperature: Optional[float] = Field(default=0.7, ge=0.0, le=2.0, description="Model sampling temperature")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional custom metadata")


class ChatResponse(BaseModel):
    """Outbound chat agent response."""
    response: str = Field(..., description="Generated answer from the model")
    session_id: Optional[str] = Field(default=None, description="Session ID")
    cached: bool = Field(default=False, description="Whether the response came from semantic cache")
    model_used: Optional[str] = Field(default=None, description="Model used for generation")
    processing_time_ms: Optional[float] = Field(default=None, description="Processing time in milliseconds")
    latency_ms: Optional[float] = Field(default=None, description="Total request latency in milliseconds")
    security_notes: List[str] = Field(default_factory=list, description="Security and guardrail notes")
    timestamp: Optional[str] = Field(default=None, description="UTC Timestamp of response")
    sources: List[SourceDocument] = Field(default_factory=list, description="Citations and retrieved documents")
    usage: Optional[TokenUsage] = Field(default=None, description="Token usage details")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Execution metadata and trace IDs")


class StreamingChatChunk(BaseModel):
    """SSE streaming response chunk payload."""
    chunk: str = Field(..., description="Incremental text fragment")
    done: bool = Field(default=False, description="True if generation is complete")
    sources: Optional[List[SourceDocument]] = Field(default=None, description="Final sources attached on completion")


# ==========================================
# 4. RAG Document Ingestion & Search Models
# ==========================================

class DocumentIngestRequest(BaseModel):
    """Payload to embed and store raw documents into vector store."""
    content: str = Field(..., min_length=1, description="Raw text to chunk and index")
    title: Optional[str] = Field(default=None, description="Document title")
    source_url: Optional[str] = Field(default=None, description="URL or origin filepath")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Custom tags and attributes")


class DocumentIngestResponse(BaseModel):
    """Ingestion confirmation."""
    document_id: str = Field(..., description="ID assigned to document")
    chunks_created: int = Field(..., description="Number of vector chunks generated")
    status: str = Field(default="indexed", description="Ingestion status")


class SearchRequest(BaseModel):
    """Direct vector or hybrid retrieval query."""
    query: str = Field(..., description="Semantic search query")
    top_k: int = Field(default=4, ge=1, le=50, description="Number of results to retrieve")
    score_threshold: Optional[float] = Field(default=None, description="Minimum similarity score filter")
    filter: Optional[Dict[str, Any]] = Field(default=None, description="Metadata filtering criteria")


class SearchResponse(BaseModel):
    """Search retrieval results."""
    results: List[SourceDocument] = Field(default_factory=list, description="Retrieved chunks")
    total_found: int = Field(..., description="Number of matched chunks")


# ==========================================
# 5. Feedback & RLHF Models (LangSmith Sync)
# ==========================================

class FeedbackRequest(BaseModel):
    """User feedback for a specific response."""
    run_id: Optional[str] = Field(default=None, description="LangSmith Run/Trace ID")
    session_id: Optional[str] = Field(default=None, description="Session ID")
    score: float = Field(..., ge=-1.0, le=1.0, description="Feedback score (e.g. 1.0 for positive, -1.0 for negative)")
    comment: Optional[str] = Field(default=None, description="Optional text feedback or correction")


class FeedbackResponse(BaseModel):
    status: str = Field(default="recorded")
    feedback_id: Optional[str] = Field(default=None)


# ==========================================
# 6. Cache & Health Models
# ==========================================

class CacheStatsResponse(BaseModel):
    """Semantic cache operational stats."""
    total_entries: int
    hit_count: int
    miss_count: int
    hit_rate_percent: float


class ComponentHealth(BaseModel):
    status: str = "healthy"
    latency_ms: Optional[float] = None
    details: Optional[str] = None


class HealthResponse(BaseModel):
    status: str = "healthy"
    service: str
    environment: str = "development"
    version: str = "1.0.0"
    components: Dict[str, ComponentHealth] = Field(default_factory=dict, description="Status of DB, Redis, LLM, Vector Store")


class ErrorResponse(BaseModel):
    """Standard error response."""
    error: str = Field(..., description="Error summary or machine-readable code")
    detail: Optional[str] = Field(default=None, description="Detailed error description or traceback")
    request_id: Optional[str] = Field(default=None, description="Unique ID for tracing the failed request")
